### ISSUE TITLE
[ckks] LinearTransform: fails with only diagonal 0

### ISSUE THREAD

**Issue by mrain** [ldsec/lattigo#111]
Will raise an "integer divided by zero" error if the matrix only contains the diagonal 0.
Related code: https://gist.github.com/mrain/9a89993569b2c43dface27ad8e413eab

**Comment by mrain** [comment]
Also check the following code. I'm trying to implementation matrix inversion using the new linear transform API. But the rotation with negative indices (or right rotations) doesn't work as expected.
https://gist.github.com/mrain/5fc14a3744b4206ef0ddcb97ac032c1e

**Comment by Pro7ech** [comment]
Hello mrain, could you tell me what branch you are working on ?

**Comment by Pro7ech** [comment]
I'm coming back with some updates. Indeed, the method EncodeDiagMatrixAtLvl wasn't encoding the diagonals at the correct index in the map if the indexes were given as centered values and not as values between 0 and slots-1. The problem should be resolved. To make sure that this was the only problem with your code, try to also run your code by encoding negative indexes instead as slots-index. Tell me if both approach work correctly (they work for the bootstrapping, so it should, but this LinearTransform hasn't yet its own test).

**Comment by mrain** [comment]
I'm working on branch dev_paper.

The division by zero problem remains after the updates. If we have <= 2 diagonals, the program will still go into the BSGS approach as the "matrix.naive" is false: https://github.com/ldsec/lattigo/blob/dev_paper/ckks/linear_transform.go#L311
This mark is never touched in the method EncodeDiagMatrixAtLvl

Also let me explain my code (the problem remains). https://gist.github.com/mrain/5fc14a3744b4206ef0ddcb97ac032c1e
I'm trying to transpose a 3x3 square matrix
`[1 2 3 4 5 6 7 8 9] 
`
into 
`[1 4 7 2 5 8 3 6 9]
`
The transition matrix has 5 diagonals:
```
 0  [1 0 0 0 1 0 0 0 1]               [1 0 0 0 5 0 0 0 9]
 2  [0 1 0 0 0 1 0 0 0]               [0 4 0 0 0 8 0 0 0]
 4  [0 0 1 0 0 0 0 0 0]               [0 0 7 0 0 0 0 0 0]
-2  [0 0 0 1 0 0 0 1 0]               [0 0 0 2 0 0 0 6 0]
-4  [0 0 0 0 0 0 1 0 0]               [0 0 0 0 0 0 3 0 0]
sum                                   [1 4 7 2 5 8 3 6 9]
```

In previous version, with negative indices, the program returns [1 4 7 0 5 8 3 0 9] where diagonal -2 is missing.
With positive indices (values between 0 and slots - 1) the program returns [1 4 7 0 5 8 0 0 9] where diagonal -2 and -4 are missiong.
In updated version both diagonal -2 and -4 are still missing. 

Also there's another interesting thing, the length of the vector here will affect the result: https://gist.github.com/mrain/5fc14a3744b4206ef0ddcb97ac032c1e#file-test-go-L18
If we change it from 16 to 9 the program will return [1 2 3 4 5 6 7 8 9]. Should it always be a power of 2?

**Comment by Pro7ech** [comment]
Hi mrain, 

I should have corrected all the bugs, I also added native tests for the LinearTransform and its 3 cases (BSGS, naive, and rotation only).

This "LinearTransform" API applies a linear transform on the ciphertext, so the diagonals of the matrix should have the size as the number of slots. Of course this can be used to emulate many smaller linear transforms, but then the diagonals must be carefully crafted.

The encoding API will accept diagonals with a negative index (indicating negative rotation of the vector), but the plaintext matrix will only have positive indexes (i.e. if you give a diagonal with index _i_, it will be return as a diagonal with index _Slots-i_)

**Comment by mrain** [comment]
Thanks very much for the fixes.

Problem for naive approach is fixed right now. There're still some problem in the BSGS approach: it doesn't work properly with negative indices (but right now it works well with indices between 0 and slots-1).

**Comment by Pro7ech** [comment]
Could you give me an example where the negative indices don't work well with the BSGS approach?

**Comment by mrain** [comment]
This is the test I ran. https://gist.github.com/mrain/d124024487d99610e7d8953fe6076144
If you uncomment line 15~17 then the result is correct.

**Comment by Pro7ech** [comment]
I fixed the last problem for the BSGS approach, which was an incorrect sign during the encoding which wasn't selecting the correct diagonal of the matrix if the index was negative. Everything should work properly now.

Thank you very much for your feedback
